name: ${COMPOSE_PROJECT_NAME}
services:
  db:
    image: ghcr.io/${GITHUB_OWNER_LC}/varsity-bets-db:latest
    container_name: varsity-bets-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_SA_USER: "${DB_USER}"
    ports:
      - "1433:1433"

  api:
    image: ghcr.io/${GITHUB_OWNER_LC}/varsity-bets-api:latest
    container_name: varsity-bets-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "5000:8080"
