name: ${COMPOSE_PROJECT_NAME}
version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: varsity-bets-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: varsity-bets-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;

volumes:
  sql-data: