using Api.Models;
using Microsoft.EntityFrameworkCore;

namespace Api.Data
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options) { }

        // Defining the tables
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<BetCategory> BetCategories { get; set; }
        public DbSet<BetSession> BetSessions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configuring the UserProfile to use FirebaseUid as the Primary Key
            modelBuilder.Entity<UserProfile>().HasKey(u => u.FirebaseUid);

            // Ensuring the FirebaseUid isn't generated by the DB (it comes from Firebase)
            modelBuilder.Entity<UserProfile>().Property(u => u.FirebaseUid).ValueGeneratedNever();

            // Setup the relationship: One User has many Sessions
            modelBuilder
                .Entity<BetSession>()
                .HasOne(s => s.User)
                .WithMany(u => u.Sessions)
                .HasForeignKey(s => s.UserProfileFirebaseUid);

            modelBuilder.Entity<BetSession>().Property(s => s.BuyInAmount).HasPrecision(18, 2);
            modelBuilder.Entity<BetSession>().Property(s => s.CashOutAmount).HasPrecision(18, 2);

            modelBuilder
                .Entity<BetCategory>()
                .HasData(
                    new BetCategory
                    {
                        Id = 1,
                        Name = "Roulette",
                        HexColor = "#E74C3C",
                        IconName = "casino",
                        Description = "Track your spins",
                    },
                    new BetCategory
                    {
                        Id = 2,
                        Name = "Blackjack",
                        HexColor = "#2C3E50",
                        IconName = "style",
                        Description = "Hit or Stand",
                    },
                    new BetCategory
                    {
                        Id = 3,
                        Name = "Slots",
                        HexColor = "#F1C40F",
                        IconName = "seven_poker",
                        Description = "Spin to win",
                    }
                );
        }
    }
}
