using Api.Models;
using Microsoft.EntityFrameworkCore;

namespace Api.Data
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options) { }

        // Defining the tables
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<BetCategory> BetCategories { get; set; }
        public DbSet<BetSession> BetSessions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configuring the UserProfile to use FirebaseUid as the Primary Key
            modelBuilder.Entity<UserProfile>().HasKey(u => u.FirebaseUid);

            // Ensuring the FirebaseUid isn't generated by the DB (it comes from Firebase)
            modelBuilder.Entity<UserProfile>().Property(u => u.FirebaseUid).ValueGeneratedNever();

            // Setup the relationship: One User has many Sessions
            modelBuilder
                .Entity<BetSession>()
                .HasOne(s => s.User)
                .WithMany(u => u.Sessions)
                .HasForeignKey(s => s.UserProfileFirebaseUid);

            // Inside ApplicationDbContext.cs -> OnModelCreating
            modelBuilder.Entity<BetSession>().Property(s => s.BuyInAmount).HasPrecision(18, 2);
        }
    }
}
